<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>BatchWatermarkExport.Cli</RootNamespace>
    <AssemblyName>BatchWatermarkExport.Cli</AssemblyName>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BatchWatermarkExport.Core\BatchWatermarkExport.Core.csproj" />
  </ItemGroup>
</Project>
